-- Ukalism Autos marketplace schema
-- Run this in Supabase SQL Editor before connecting live vehicle inventory.

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  title text not null,
  make text not null,
  model text not null,
  year integer not null check (year between 1900 and 2100),
  condition text not null check (condition in ('Brand New', 'Foreign Used', 'Nigerian Used')),
  price text not null,
  location text not null,
  mileage integer not null default 0 check (mileage >= 0),
  transmission text not null,
  fuel_type text not null,
  body_type text not null,
  images text[] not null default '{}',
  video_url text,
  description text not null default '',
  features text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vehicles enable row level security;

grant select on table public.vehicles to anon, authenticated;
grant insert, update, delete on table public.vehicles to authenticated;
grant usage, select on sequence public.vehicles_id_seq to authenticated;

drop policy if exists "Public can read vehicles" on public.vehicles;
create policy "Public can read vehicles"
on public.vehicles for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert vehicles" on public.vehicles;
create policy "Admin can insert vehicles"
on public.vehicles for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

drop policy if exists "Admin can update vehicles" on public.vehicles;
create policy "Admin can update vehicles"
on public.vehicles for update
to authenticated
using ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com')
with check ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

drop policy if exists "Admin can delete vehicles" on public.vehicles;
create policy "Admin can delete vehicles"
on public.vehicles for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

create or replace function public.set_vehicle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at
before update on public.vehicles
for each row execute function public.set_vehicle_updated_at();

insert into public.vehicles
  (id, title, make, model, year, condition, price, location, mileage, transmission, fuel_type, body_type, images, description, features)
values
  (1, '2021 Toyota Highlander XLE', 'Toyota', 'Highlander XLE', 2021, 'Foreign Used', '₦41,999,998', 'Lagos, Nigeria', 85000, 'Automatic', 'Petrol', 'SUV', array['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85'], 'A practical premium SUV concept for families and executives looking for comfort, space and everyday usability in Lagos.', array['Automatic transmission','Petrol engine','Spacious cabin','Premium interior','Reverse camera'])
on conflict (id) do nothing;

insert into public.vehicles
  (id, title, make, model, year, condition, price, location, mileage, transmission, fuel_type, body_type, images, description, features)
values
  (2, '2020 Toyota Camry XSE', 'Toyota', 'Camry XSE', 2020, 'Foreign Used', '₦28,000,000', 'Lagos, Nigeria', 34000, 'Automatic', 'Petrol', 'Sedan', array['https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=85'], 'A clean executive sedan concept with a comfortable cabin, modern styling and strong everyday road presence.', array['Automatic transmission','Petrol engine','Leather interior','Touchscreen display','Parking sensors'])
on conflict (id) do nothing;

insert into public.vehicles
  (id, title, make, model, year, condition, price, location, mileage, transmission, fuel_type, body_type, images, description, features)
values
  (3, '2019 Honda Accord Sport', 'Honda', 'Accord Sport', 2019, 'Nigerian Used', '₦18,700,000', 'Lagos, Nigeria', 45000, 'Automatic', 'Petrol', 'Sedan', array['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85'], 'A polished sedan concept suited to buyers looking for a balanced mix of comfort, performance and value.', array['Automatic transmission','Petrol engine','Sport trim','Touchscreen display','Alloy wheels'])
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.vehicles', 'id'), greatest(coalesce((select max(id) from public.vehicles), 1), 1), true);
