-- Ukalism marketplace enquiries
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  listing_type text not null check (listing_type in ('property', 'vehicle')),
  listing_id bigint not null,
  listing_title text not null,
  name text not null,
  phone text not null,
  email text,
  message text not null default '',
  status text not null default 'New Lead' check (status in ('New Lead','Contacted','Replied','Interested','Viewing / Inspection','Proposal / Negotiation','Won','Lost')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

grant insert on table public.enquiries to anon, authenticated;
grant select, update, delete on table public.enquiries to authenticated;
grant usage, select on sequence public.enquiries_id_seq to anon, authenticated;

drop policy if exists "Public can submit enquiries" on public.enquiries;
create policy "Public can submit enquiries"
on public.enquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "Admin can read enquiries" on public.enquiries;
create policy "Admin can read enquiries"
on public.enquiries for select
to authenticated
using ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

drop policy if exists "Admin can update enquiries" on public.enquiries;
create policy "Admin can update enquiries"
on public.enquiries for update
to authenticated
using ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com')
with check ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

drop policy if exists "Admin can delete enquiries" on public.enquiries;
create policy "Admin can delete enquiries"
on public.enquiries for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'deejayjohnkay@gmail.com');

create or replace function public.set_enquiry_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists enquiries_set_updated_at on public.enquiries;
create trigger enquiries_set_updated_at
before update on public.enquiries
for each row execute function public.set_enquiry_updated_at();