-- Ukalism Real Estate property database + admin security
-- Run this in Supabase SQL Editor.
-- IMPORTANT: replace YOUR_ADMIN_EMAIL with the exact email you will use for the admin account.

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  type text not null check (type in ('For Sale', 'For Rent')),
  category text not null check (category in ('House', 'Apartment', 'Land')),
  price text not null,
  beds integer,
  baths integer,
  area text,
  images text[] not null default '{}',
  description text not null default '',
  features text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.properties enable row level security;

-- Public visitors can read published listings.
drop policy if exists "Public can read properties" on public.properties;
create policy "Public can read properties"
on public.properties
for select
to anon, authenticated
using (true);

-- Only the configured admin email can create, edit or delete listings.
drop policy if exists "Admin can insert properties" on public.properties;
create policy "Admin can insert properties"
on public.properties
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

drop policy if exists "Admin can update properties" on public.properties;
create policy "Admin can update properties"
on public.properties
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL')
with check ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

drop policy if exists "Admin can delete properties" on public.properties;
create policy "Admin can delete properties"
on public.properties
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

-- Keep updated_at current whenever an admin edits a listing.
create or replace function public.set_property_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists properties_set_updated_at on public.properties;
create trigger properties_set_updated_at
before update on public.properties
for each row execute function public.set_property_updated_at();

-- Seed the three demo listings currently used by the website.
insert into public.properties
  (id, title, location, type, category, price, beds, baths, area, images, description, features)
values
  (1,
   'Luxury 4-Bedroom Detached Duplex',
   'Lekki Phase 1, Lagos',
   'For Sale',
   'House',
   '₦185,000,000',
   4,
   5,
   '450 sqm',
   array[
     'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=90'
   ],
   'A premium residential property concept designed for families seeking generous living spaces, contemporary finishes and a comfortable environment in Lekki Phase 1. This demonstration listing showcases the type of property information Ukalism Real Estate can present to prospective clients.',
   array['Detached duplex','4 spacious bedrooms','5 bathrooms','Large living and dining areas','Modern fitted kitchen','Private parking space','Secure residential environment','450 sqm land size'])
on conflict (id) do nothing;

insert into public.properties
  (id, title, location, type, category, price, beds, baths, area, images, description, features)
values
  (2,
   'Modern 3-Bedroom Apartment',
   'Ikoyi, Lagos',
   'For Rent',
   'Apartment',
   '₦12,000,000 / year',
   3,
   3,
   '220 sqm',
   array[
     'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90'
   ],
   'A contemporary apartment concept for clients looking for comfortable city living in Ikoyi. The demonstration listing highlights modern interiors, practical living spaces and a convenient location close to business, lifestyle and leisure destinations.',
   array['3 spacious bedrooms','3 bathrooms','Modern fitted kitchen','Spacious living room','Contemporary finishes','Secure residential environment','Prime Ikoyi location','220 sqm'])
on conflict (id) do nothing;

insert into public.properties
  (id, title, location, type, category, price, beds, baths, area, images, description, features)
values
  (3,
   'Premium Residential Land',
   'Sangotedo, Lagos',
   'For Sale',
   'Land',
   '₦45,000,000',
   null,
   null,
   '600 sqm',
   array[
     'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=90',
     'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=90'
   ],
   'A residential land demonstration listing in Sangotedo for buyers considering future development or long-term property investment. The listing illustrates how Ukalism Real Estate can present land opportunities and guide prospective buyers through their next enquiry.',
   array['600 sqm residential land','Suitable for residential development','Growing neighbourhood','Accessible location','Investment potential','Suitable for family home'])
on conflict (id) do nothing;

-- Make future generated IDs continue after the seeded records.
select setval(
  pg_get_serial_sequence('public.properties', 'id'),
  greatest(coalesce((select max(id) from public.properties), 1), 1),
  true
);
