import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, Edit3, LogOut, Plus, Save, Trash2, X } from 'lucide-react'
import { ADMIN_EMAIL, supabase } from '../lib/supabase'
import MediaUploader from './MediaUploader'
import './AdminPage.css'

const emptyForm = { title:'', location:'', type:'For Sale', category:'House', price:'', beds:'', baths:'', area:'', images:[], videoUrl:'', description:'', features:'' }
const toArray = (value) => Array.isArray(value) ? value : []
const rowToForm = (p) => ({ title:p.title||'', location:p.location||'', type:p.type||'For Sale', category:p.category||'House', price:p.price||'', beds:p.beds??'', baths:p.baths??'', area:p.area||'', images:toArray(p.images), videoUrl:p.video_url||'', description:p.description||'', features:Array.isArray(p.features)?p.features.join('\n'):'' })
const formToRow = (f) => ({ title:f.title.trim(), location:f.location.trim(), type:f.type, category:f.category, price:f.price.trim(), beds:f.beds===''?null:Number(f.beds), baths:f.baths===''?null:Number(f.baths), area:f.area.trim(), images:f.images.filter(Boolean), video_url:f.videoUrl.trim()||null, description:f.description.trim(), features:f.features.split('\n').map(v=>v.trim()).filter(Boolean) })

function AdminPage(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[authLoading,setAuthLoading]=useState(false),[email,setEmail]=useState(ADMIN_EMAIL),[password,setPassword]=useState(''),[properties,setProperties]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const isAdmin=useMemo(()=>session?.user?.email?.toLowerCase()===ADMIN_EMAIL?.toLowerCase(),[session])
 useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data})=>{if(mounted){setSession(data.session);setLoading(false)}});const {data:listener}=supabase.auth.onAuthStateChange((_e,s)=>{if(mounted){setSession(s);setLoading(false)}});return()=>{mounted=false;listener.subscription.unsubscribe()}},[])
 useEffect(()=>{if(isAdmin)loadProperties()},[isAdmin])
 async function loadProperties(){setError('');const {data,error:e}=await supabase.from('properties').select('*').order('id',{ascending:true});if(e)setError(e.message);else setProperties(data||[])}
 async function login(e){e.preventDefault();setAuthLoading(true);setError('');const {error:e2}=await supabase.auth.signInWithPassword({email:email.trim(),password});setAuthLoading(false);if(e2)setError(e2.message);else setPassword('')}
 async function logout(){await supabase.auth.signOut();setProperties([]);setEditingId(null);setForm(emptyForm)}
 const update=(field,value)=>setForm(v=>({...v,[field]:value}))
 const startCreate=()=>{setEditingId(null);setForm(emptyForm);setMessage('');setError('')}
 const startEdit=(p)=>{setEditingId(p.id);setForm(rowToForm(p));setMessage('');setError('');window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e){e.preventDefault();setSaving(true);setError('');setMessage('');const payload=formToRow(form);if(!payload.title||!payload.location||!payload.price){setSaving(false);setError('Title, location and price are required.');return}const result=editingId?await supabase.from('properties').update(payload).eq('id',editingId):await supabase.from('properties').insert(payload);setSaving(false);if(result.error){setError(result.error.message);return}setMessage(editingId?'Property updated successfully.':'Property added successfully.');setEditingId(null);setForm(emptyForm);await loadProperties()}
 async function remove(p){if(!window.confirm(`Delete “${p.title}”? This cannot be undone.`))return;const {error:e}=await supabase.from('properties').delete().eq('id',p.id);if(e)setError(e.message);else{setMessage('Property deleted.');await loadProperties()}}
 if(loading)return <div className="admin-loading">Loading admin portal…</div>
 if(!session)return <main className="admin-shell admin-login-shell"><div className="admin-login-card"><button className="admin-back" onClick={()=>window.location.href='/'}><ArrowLeft size={17}/> Back to website</button><div className="admin-brand-mark">U</div><span className="admin-eyebrow">UKALISM PROPERTIES & AUTOS</span><h1>Admin Portal</h1><p>Sign in to manage published property listings.</p>{error&&<div className="admin-alert error">{error}</div>}<form onSubmit={login} className="admin-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="admin-primary-button" disabled={authLoading}>{authLoading?'Signing in…':'Sign in'}</button></form></div></main>
 if(!isAdmin)return <main className="admin-shell admin-login-shell"><div className="admin-login-card"><div className="admin-brand-mark">U</div><span className="admin-eyebrow">UKALISM PROPERTIES & AUTOS</span><h1>Access denied</h1><p>The signed-in account is not authorised to manage this website.</p><button className="admin-primary-button" onClick={logout}>Sign out</button></div></main>
 return <main className="admin-shell"><header className="admin-header"><div><span className="admin-eyebrow">UKALISM PROPERTIES & AUTOS</span><h1>Property Management</h1><p>Signed in as {session.user.email}</p></div><div className="admin-header-actions"><button className="admin-secondary-button" onClick={()=>window.location.href='/'}><ArrowLeft size={17}/> Website</button><button className="admin-secondary-button" onClick={logout}><LogOut size={17}/> Sign out</button></div></header><section className="admin-content"><div className="admin-toolbar"><div><strong>{properties.length}</strong> published properties</div><button className="admin-primary-button" onClick={startCreate}><Plus size={18}/> Add property</button></div>{message&&<div className="admin-alert success"><Check size={17}/> {message}</div>}{error&&<div className="admin-alert error">{error}</div>}
 <form className="property-editor" onSubmit={save}><div className="editor-heading"><div><span className="admin-eyebrow">{editingId?'EDIT LISTING':'NEW LISTING'}</span><h2>{editingId?'Edit property':'Add a property'}</h2></div>{editingId&&<button type="button" className="icon-button" onClick={()=>{setEditingId(null);setForm(emptyForm)}} aria-label="Cancel editing"><X size={19}/></button>}</div><div className="editor-grid"><label>Property title *<input value={form.title} onChange={e=>update('title',e.target.value)} required/></label><label>Location *<input value={form.location} onChange={e=>update('location',e.target.value)} required/></label><label>Listing type<select value={form.type} onChange={e=>update('type',e.target.value)}><option>For Sale</option><option>For Rent</option></select></label><label>Property type<select value={form.category} onChange={e=>update('category',e.target.value)}><option>House</option><option>Apartment</option><option>Land</option></select></label><label>Price *<input value={form.price} onChange={e=>update('price',e.target.value)} placeholder="₦185,000,000" required/></label><label>Area<input value={form.area} onChange={e=>update('area',e.target.value)} placeholder="450 sqm"/></label><label>Bedrooms<input type="number" min="0" value={form.beds} onChange={e=>update('beds',e.target.value)}/></label><label>Bathrooms<input type="number" min="0" value={form.baths} onChange={e=>update('baths',e.target.value)}/></label></div>
 <div className="admin-media-field"><span className="admin-media-label">Listing media</span><MediaUploader images={form.images} videoUrl={form.videoUrl} onImagesChange={v=>update('images',v)} onVideoChange={v=>update('videoUrl',v)} folder={editingId?`properties/${editingId}`:'properties/new'}/></div>
 <label>Description<textarea rows="5" value={form.description} onChange={e=>update('description',e.target.value)}/></label><label>Features<textarea rows="5" value={form.features} onChange={e=>update('features',e.target.value)} placeholder="One feature per line"/></label><div className="editor-actions">{editingId&&<button type="button" className="admin-secondary-button" onClick={()=>{setEditingId(null);setForm(emptyForm)}}>Cancel</button>}<button type="submit" className="admin-primary-button" disabled={saving}><Save size={18}/> {saving?'Saving…':editingId?'Save changes':'Publish property'}</button></div></form>
 <section className="admin-list"><div className="list-heading"><div><span className="admin-eyebrow">LIVE INVENTORY</span><h2>Published properties</h2></div></div>{properties.length===0?<div className="empty-state">No properties have been published yet.</div>:<div className="property-admin-grid">{properties.map(p=><article className="property-admin-card" key={p.id}><div className="property-admin-image">{p.images?.[0]&&<img src={p.images[0]} alt={p.title}/>}<span>{p.type}</span></div><div className="property-admin-body"><span>{p.location}</span><h3>{p.title}</h3><strong>{p.price}</strong><div className="property-admin-actions"><button className="admin-secondary-button" onClick={()=>startEdit(p)}><Edit3 size={16}/> Edit</button><button className="admin-danger-button" onClick={()=>remove(p)}><Trash2 size={16}/> Delete</button></div></div></article>)}</div>}</section></section></main>
}
export default AdminPage
